### ISSUE TITLE
Improve JRuby testing

### ISSUE THREAD

**Issue by v0dro** [SciRuby/daru#122]
Few things that come immediately to mind:
- Change travis for including JRuby.
- Make sure all the valid specs that are supposed to be running in JRuby are actually running.

**Comment by lokeshh** [comment]
This is the output I got running bundle install with jruby https://gist.github.com/lokeshh/b50ebccd7fcf430ea8d593ec8e6abe9f

Some of the things that needs change:
- Make Nyaplot jruby compatible
- Byebug doesn't work with JRuby, so it has to be removed
- Get some problems with Installing sqlite3 1.3.11 with native extensions
- Get some problems with Installing gsl 2.1.0.1 with native extensions

**Comment by v0dro** [comment]
OK. Open an issue in nyaplot that it's not compatible with JRuby yet. I think it's some minor issue regarding ruby version which will need a small fix.

Let byebug be, but find other JRuby compatible alternatives for sqlite3 (I'm sure there is one since it's a widely used gem by the Rails community). We'll need to see if it's possible to not include byebug and gsl as development dependencies when the tests are being run with JRuby.

**Comment by zverok** [comment]
NB: In fact, Nyaplot is compatible with JRuby, but is not compatible with Ruby < 2, so it is easily installed with JRuby 9.0.x.x, but will not install to versions prior to that (which are equivalent to Ruby 1.9).

**Comment by v0dro** [comment]
I just figured that you can install dependencies according to interpreter with install_if or platform.

https://github.com/bundler/bundler/blob/dfdeb0f89e7e88fcdfd001da089f09af3a77d2b4/man/gemfile.5.ronn#L454

**Comment by v0dro** [comment]
JRuby is no longer a priority. Might reopen later but closing for now.
