### ISSUE TITLE
Read/write .csv.gz

### ISSUE THREAD

**Issue by zverok** [SciRuby/daru#127]
**Reason**: in R world, for example, its common thing to provide `.csv.gz` form of datasets for studying something. And it have a great sense: in many examples, `.csv.gz` files are 10-20 times smaller than respective `.csv` files. 

Sample code to read data from `.csv.gz`:

``` ruby
require 'zlib'
gz = Zlib::GzipReader.new(File.open(path, 'rb'))
csv = CSV.new(gz)
```

One quick benchmark on my test data from other project:
- "kladr.csv" is 33'656'305 bytes
- "kladr.csv.gz" is 1'976'287 (17 times smaller)

Benchmark code:

``` ruby
require 'benchmark'
require 'csv'
require 'zlib'

Benchmark.bm do |x|
  x.report(".csv") do
    CSV.foreach('kladr.csv') do |r|
    end
  end

  x.report(".csv.gz") do
    gz = Zlib::GzipReader.new(File.open('kladr.csv.gz', 'rb'))
    CSV.new(gz).each do |r|
    end
  end
end
```

Benchmark results:

```
          user     system      total        real
.csv    3.930000   0.010000   3.940000 (  3.934296)
.csv.gz 4.220000   0.010000   4.230000 (  4.224610)
```

Only 7% slower!

**Comment by v0dro** [comment]
This can be in a `DataFrame.from_csv_gz()` function.

**Comment by zverok** [comment]
BTW, in R its just `read_csv` (like, "we don't mind if your csv is packed"), but I'm not sure it is good approach :)

**Comment by parthm** [comment]
It might be worth having an option like `compression : {‘infer’, ‘gzip’, ‘bz2’, ‘zip’, ‘xz’, None}, default ‘infer’` for `from_csv`. This is how [pandas.read_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) handles this. This way even if only `gz` support gets implemented initially, it can be extended to support other formats as well going forward without any API change. Also, user transition might be easier for those coming from `pandas`.

**Comment by v0dro** [comment]
I like what @parthm is saying. I think we should use his suggestion for the implementation. @athityakumar can you add this issue to the daru-io repo?

**Comment by athityakumar** [comment]
@v0dro - Acknowledged. Filed an issue to track this in daru-io. Should `from_csv` redirect to `from_csv_gz` depending on the extension, or would it be better to have a `compression` option?

**Comment by v0dro** [comment]
A compression option is better.

**Comment by zverok** [comment]
Closing as related to (and implemented in) daru-io
