### ISSUE TITLE
Change #dv to #to_dv?

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/daru#131]
Array or ranges can be initialized to `Daru::Vector` with `dv` method like

``` ruby
[15] pry(main)> (1..3).dv
=> 
#<Daru::Vector:22990900 @name = nil @metadata = {} @size = 3 >
    nil
  0   1
  1   2
  2   3
```

I think `to_dv` is better because its intuitive and easy to remember similar to `to_i`, `to_a`, etc.

**Comment by zverok** [comment]
+1 to this proposition.
Also, I'm not sure it is a good practice to pollute Ruby objects with such a short names. 
I'd prefer having `Array#to_daru_vector` by default, and `to_dv` shortcut defined in something like `daru/shortcuts` (not required by default).

**Comment by v0dro** [comment]
Ok works. `to_dv` is better and more suited for a Ruby class change.

**Comment by zverok** [comment]
Closing in favor if #424
