### ISSUE TITLE
[API] Better support for SQL databases

### ISSUE THREAD

**Issue by zverok** [SciRuby/daru#138]
This is multipart proposal.

**First**: Change method name: `from_sql`s intuitive understanding is "from SQL database dump" (file or string, containing something like `INSERT INTO ... VALUES ...` -- such dumps any database could produce and in some context it is a common format for data exchange), which is not the case. 

I think `from_db` could express the intention better.

**Second**: as far as I can see in practice, there are 3 distinct cases we need to cover for easy loading data from DB:
- load entire table into the dataframe;
- load some columns of table into the dataframe;
- load results of some SQL query into the dataframe.

So, the most reasonable API is:

``` ruby
DataFrame.from_db(adapter, table: 'tbl')
DataFrame.from_db(adapter, table: 'tbl', columns: [:id, :name, :gender])
DataFrame.from_db(adapter, query: 'SELECT * FROM employees JOIN departments...' )
```

`columns` param could be provided with the `query` also. And also, it can be a hash, or mix of array/hash, for column renaming while loading:

``` ruby
DataFrame.from_db(adapter, table: 'tbl', columns: [:id, Name: :name, employee_gender: :gender])
```

**Comment by v0dro** [comment]
Alright. We should keep compatibility with `from_sql` because many people use that. The enhanced behavior looks good.

**Comment by dansbits** [comment]
Just throwing my cents in here. 

1. I don't have any strong opinions on naming for the method but I'd be curious to hear more rationale for the change. The pandas method is `read_sql` so I don't think it's non-standard to use sql instead of db. Do you have any examples of other libraries which use db instead of sql? I agree that continued support of from_sql or at least a deprecation period would be a good idea.

2. It seems like the first two cases can be easily handled directly in a very basic SQL query. Is it worth the additional complexity in the method?

Just wanting to better understand the motivations behind the changes and happy to discuss.

**Comment by zverok** [comment]
>  Do you have any examples of other libraries which use db instead of sql?

Not sure about it. That was rather "personal taste-based" than "example-based" suggestion. But it can be considered other way round: `from_sql` means import from _SQL database_ (in constranst for some No-SQL or specialized databases). So, I suppose, current name should work also.

> It seems like the first two cases can be easily handled directly in a very basic SQL query. Is it worth the additional complexity in the method?

Yeah, I think it is. First, not everyone is familiary with SQL (and there would be constant need for some users for refering to docs about this `SELECT * FROM table` or was it `FETCH FROM table (*)` or should I use some kinde of parens, or waht); second, shortening most common cases is almost always a good thing (at least, for my taste), and Ruby's keyword arguments allow to handle it gracefully. Personally, I'd hate the necessity to write `from_sql(adapter, 'SELECT * FROM employees')` each and every time for quick fire-and-forget experimental scripts.

**Comment by gnilrets** [comment]
I also prefer `from_sql`.  Not everything that supports SQL(-like) syntax is a "database".  For example, Salesforce and Apache Spark are not traditional databases, but can both be accessed using a SQL-like syntax.

**Comment by lokeshh** [comment]
I think we can use [ActiveRecord](https://github.com/rails/rails/tree/master/activerecord) gem to support queries such as 

```ruby
User.where(name: 'David', occupation: 'Code Artist').order(created_at: :desc)
```

which is way simpler than (SELECT * ...) and quite popular because of Rails.

**Comment by v0dro** [comment]
+1 to @lokeshh though the implementation of that would need to be looked into. And I agree with @gnilrets about `from_sql`. We should ideally be able to swap out the underlying SQL adapter in the future in order to accommodate for Spark or Salesforce.

> Yeah, I think it is. First, not everyone is familiary with SQL (and there would be constant need for some users for refering to docs about this SELECT * FROM table or was it FETCH FROM table (*) or should I use some kinde of parens, or waht); second, shortening most common cases is almost always a good thing (at least, for my taste), and Ruby's keyword arguments allow to handle it gracefully. Personally, I'd hate the necessity to write from_sql(adapter, 'SELECT * FROM employees') each and every time for quick fire-and-forget experimental scripts.

@zverok agreed.

**Comment by zverok** [comment]
@lokeshh 

> In addition, I think we can use ActiveRecord gem to support queries such as

How do you imagine it? If by adding direct integration/dependencies, I'd be pretty much against it.

**Comment by v0dro** [comment]
Maybe put in a separate gem (`daru-activerecord`?) that depends on both activerecord and daru for doing this.

**Comment by zverok** [comment]
Closing in favor of daru-io
