### ISSUE TITLE
[API] Rename Vector#is_nil?

### ISSUE THREAD

**Issue by zverok** [SciRuby/daru#141]
As the method not returns boolean (the only thing that predicate methods should return), it definitely shouldn't contain question mark in the name.

So, my proposal here is `#is_nil?` => `#nils`, `#not_nil?` => `#not_nils`.

**Comment by v0dro** [comment]
Ok agreed.

**Comment by v0dro** [comment]
now that you mention it, I just found a bug in the method. It's not working for missing values other than nil:
```
2.2.1 :048 > q=Daru::Vector.new([1,2,3,4,5,5,5,6,3,2], missing_values: [5,4])
 => 
#<Daru::Vector:79774490 @name = nil @metadata = {} @size = 10 >
    nil
  0   1
  1   2
  2   3
  3   4
  4   5
  5   5
  6   5
  7   6
  8   3
  9   2
 
2.2.1 :049 > q.missing_values
 => [nil, 5, 4] 
2.2.1 :050 > q.is_nil?
 => 
#<Daru::Vector:79564640 @name = nil @metadata = {} @size = 10 >
        nil
    0   nil
    1   nil
    2   nil
    3   nil
    4   nil
    5   nil
    6   nil
    7   nil
    8   nil
    9   nil
```

**Comment by zverok** [comment]
> now that you mention it, I just found a bug in the method. It's not working for missing values other than nil

Which returns us to https://github.com/v0dro/daru/issues/137, and especially the bold statement: 

> to be honest, I'm not sure even inside Daru always used correctly -- there are ton of simple nil-checks here and there, and eventual "right" missing-data checks

;)

**Comment by zverok** [comment]
> Ok agreed, but the resultant vector has nil or true values. What do you propose keeping that in mind?

I think it's pretty easy to explain (and understand) something like "`Vector#nils` returns vector of booleans of same size as original, having `true` in places where original vector have `nil`, and `false` where it is not". WDYT?

**Comment by v0dro** [comment]
Ok I'm convinced.

**Comment by v0dro** [comment]
@lokeshh has this been taken care of in your missing values PR?

**Comment by lokeshh** [comment]
No

**Comment by lokeshh** [comment]
Should `#nils` return `true` for places where value is `Float::NAN`? Perhaps we can implement a more generic function like `values?(*values)` which would return `true` for positions which have any value in `*values`. For example:
```ruby
> dv = Daru::Vector.new [1, 2, 3, nil, Float::NAN, nil]
> dv.values? nil, 1, Float::NAN
# => [true, false, false, true, true, true]
```

Also, should we return an array or vector?

**Comment by v0dro** [comment]
> Also, should we return an array or vector?
Return a `BoolArray`.

**Comment by lokeshh** [comment]
Ok... And What will be a good name? We cannot name is `values?` because as Victor mentioned it isn't returning a true/false?

**Comment by zverok** [comment]
I'd say that temptation to make it question-marked is big, but we should resist!
Therefore, the name maybe should inform exactly what it does, like `existance_vector` or `equality_vector` or something like this?
