### ISSUE TITLE
[Cleanup] Vector#to_s and DataFrame#to_s should return something reasonable

### ISSUE THREAD

**Issue by zverok** [SciRuby/daru#142]
...now they are synonyms for `#to_html`, so, `puts Daru::Vector([1,2,3])` will produce pretty strange result for newcomer.

**Comment by gnilrets** [comment]
I think this is done so that `Daru::DataFrame.new({ a: [1,2,3] })` will produce a nice table output in iRuby.  Otherwise, the user would have to explicitly call `#to_html` in iRuby to see the nice tables.

When I'm not working in iRuby and I need to inspect data in a dataframe, I usually just call `#to_a`.

**Comment by v0dro** [comment]
@gnilrets is right. However if iruby has some method that allows us to convert to iruby compatible pretty printing we can use that instead of `to_s`.

**Comment by zverok** [comment]
If I'm reading current IRuby's [code](https://github.com/SciRuby/iruby/blob/4fa06a9e828a2868af5441afab3773014eedb38f/lib/iruby/display.rb#L246) correctly, it outputs `obj.to_html` if object responds to `#to_html`, therefore no needs to output HTML for `#to_s`.

Moreover, if you'll read the file by my link from top to bottom, there is _no_ place where attempt to `#to_s` the object is made: the [last resort](https://github.com/SciRuby/iruby/blob/4fa06a9e828a2868af5441afab3773014eedb38f/lib/iruby/display.rb#L285) is `#inspect`.

**Comment by v0dro** [comment]
Hmmm I'll just try that out in an iruby notebook and post it here.

**Comment by v0dro** [comment]
@zverok you're right. It does indeed make use of to_html (not sure in which version they introduced this change).

I made some changes to my local daru install and here's the output:
![screenshot from 2016-05-29 01 39 03](https://cloud.githubusercontent.com/assets/2629909/15629741/b2d8d404-253e-11e6-85d3-f4d125a1bef4.png)

**Comment by zverok** [comment]
Yeah, I've investigated the matters thorougly preparing my reality for IRuby compatibility :) Current behavior seems much more logical than relying upon `#to_s`

**Comment by zverok** [comment]
OK, I see several possible options for `#to_s`:

1. just synonym for `#inspect`;
2. more fancy table formatting (like [terminal-table](https://github.com/tj/terminal-table) allows);
3. short string of header-only, like "<Daru::DataFrame(3x5)>" and that's all.

Of them, opt.1 is the simplest we can do :), opt.2 produces the most reasonable result for `puts dataframe`, and opt.3 produces the most reasonable result for `raise ArugmentError, "You should provide Integer, #{variable} received"` (with `variable` eventually turning up to be DF/Vector).

**Comment by v0dro** [comment]
I would go with `3.` simply because inspect is more of diving deeper into the data structure while `to_s` is like short stringified representation. `2` can also be done separately in a `#terminal_table` method.

**Comment by baarkerlounger** [comment]
Think this can be closed given the above merged PR.
