### ISSUE TITLE
[API] Redesign of `DataFrame#group_by`

### ISSUE THREAD

**Issue by zverok** [SciRuby/daru#152]
Planned to do this myself, but, unfortunately, in upcoming weeks I will have much less spare time. So, just writing it here to not forget.

**The idea**: we don't need separate `Core::GroupBy` object. It adds to users confusion, code and tests complexity and makes grouping too rigid and fragile.

**The solution**:
**_Part 1_**: make `DataFrame#group_by` to produce DF with MultiIndex, like this:

``` ruby
df = Daru::DataFrame.new(
  employee: %w[John Jane Mark John Jane Mark],
  month: %w[June June June July July July],
  salary: [1000, 500, 700, 1200, 600, 600]
)
# => #<Daru::DataFrame(6x3)>
#          employee    month   salary
#        0     John     June     1000
#        1     Jane     June      500
#        2     Mark     June      700
#        3     John     July     1200
#        4     Jane     July      600
#        5     Mark     July      600 

df.group_by(:employee)
# => #<Daru::DataFrame(6x2)>
#                month salary
#   John      0   June   1000
#             3   July   1200
#   Jane      1   June    500
#             4   July    600
#   Mark      2   June    700
#             5   July    600 
```

I think, it is pretty intuitive (in fact, that was what I've expected when first met with Daru) -- we just have MultiIndex of summary column + source index.

**_Part 2_**: Add `DataFrame#summarize` for multi-indexed DFs, like this (considering DF above):

``` ruby
df.group_by(:employee).summarize(salary: :sum)
# => #<Daru::DataFrame(3x2)>
#         month salary
#   John   June   2200
#   Jane   June   1100
#   Mark   June   1300 
```

Things to note:
- all index parts except first column are dropped (for wide indexes we can have first param of how many columns of index to take)
- default operation (for "month" column) is just take a first of each group;
- we can provide operation (as for "salary") column in form of symbol or lambda.

Another example with same DF:

``` ruby
df.group_by(:employee)
  .summarize(
    salary: :sum,
    month: ->(vec) { vec.to_a.join('/') } # argument for lambda is grouped part of vector
  )
# => #<Daru::DataFrame(3x2)>
#               month    salary
#      John June/July      2200
#      Jane June/July      1100
#      Mark June/July      1300 
```

And another one:

``` ruby
df.group_by(:employee)
  .summarize(
    salary: :sum,
    month: ->(vec) { vec.to_a.join('/') },
    mean_salary: ->(df) { df.salary.mean }, # when column name is not in orig.DF,
    periods: ->(df) { df.size }             # argument is part of entire dataframe
                                            # belonging to the group
  )

# => #<Daru::DataFrame(3x4)>
#                 month     salary mean_salar    periods
#       John  June/July       2200       1100          2
#       Jane  June/July       1100        550          2
#       Mark  June/July       1300        650          2 
```

WDYT?

**Comment by gnilrets** [comment]
I agree the `Core::GroupBy` is a little weird at first.  In general I like this, but I have a few comments/suggestions.

1 - The grouped vectors should remain in the dataframe as well as being part of the index, since we may need to refer to them as they appeared originally.  So in in your first example:

````ruby
df.group_by(:employee)
# => #<Daru::DataFrame(6x2)>
#                employee month salary
#   John      0      John  June   1000
#             3      John  July   1200
#   Jane      1      Jane  June    500
#             4      Jane  July    600
#   Mark      2      Mark  June    700
#             5      Mark  July    600 
````

2 - For the last two examples, would you need to create a vector/dataframe for every group?  I imagine that could be very expensive.  I've been noticing lately some substantial performance issues when the `number of groups:number of records` ratio is large.  When there are only a few groups, it works great, and ideally we should keep good performance even when the number of groups increases.

**Comment by zverok** [comment]
About (1) I may agree (it looks a bit redundant, but in real-life cases I think it would be necessary).

About (2) -- one of my biggest concerns (and reasons I'm here) is: I want to have Vector/DataFrame as natural in Ruby community as Array and Hash are. This means both speed and usability.
One of the things I'm really aware of is that creation of Vectors and DFs on the fly for small reasons **should** be cheap, and I'm constantly aiming in this direction. 

So, for ex., as in other Ruby code you do something like `array.each_cons(2)` and absolutely not bothered about the fact that it produces whole new disposable Array objects only for this small matter of "enumerating each pair" -- I want daru core objects to achieve the same (so that even most of daru internal functions can use them, not those optimization tricks of "OK, take everything as a plain arrays, do the complex data manipulations, than recreate vectors/dataframes).

**Comment by v0dro** [comment]
Yes looks good to me.

**Comment by zverok** [comment]
Comments added by this commit: https://github.com/v0dro/daru/pull/257/commits/96028865536466b219625b36aea05514e8730c86 should be considered on `group_by` redesign: it will affect `pivot_table` behavior (and, if everything will work, affect in a good way!)

**Comment by v0dro** [comment]
OK I'll have a look.

**Comment by Shekharrajak** [comment]
For part 1, I think we should make MultiIndex having same number of layers as number of element to be grouped. So now `employee` will be MultiIndex having MultiIndex name as `employee`. Then using `.groups` or `.get_group` we can map the `Index` and then other `df` vectors, right ?

**Comment by zverok** [comment]
> So now employee will be MultiIndex having MultiIndex name as employee.

Right.

> Then using .groups or .get_group we can map the Index and then other df vectors, right

I don't think that we will need methods with those names, standard DF API should be enough for everything that `get_group` currently does.

**Comment by Shekharrajak** [comment]
Thanks @zverok , I have done some work on Part 1 in https://github.com/SciRuby/daru/pull/330 . Please have a look.

**Comment by zverok** [comment]
Not sure why it is closed. I pressed the wrong button?.. :philosoraptor:
