### ISSUE TITLE
Vector initialization failed when dtype is nmatrix

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/daru#153]
Vector containing `nil`s can't be initialized using `:nmatrix` even though nmatrix supports `nil`'s.

``` ruby
[12] pry(main)> x = Daru::Vector.new [2, nil], dtype: :nmatrix
TypeError: no implicit conversion from nil to integer
from /home/ubuntu/workspace/daru/lib/daru/accessors/nmatrix_wrapper.rb:28:in `initialize'
```

(Discovered this while working with https://github.com/v0dro/daru/pull/134; writing it down in case I forget it.)

**Comment by v0dro** [comment]
You'll need to specify `:nm_dtype` as `:object` or alternatively catch the error and change the required data type to `:object` from the default `:int32`.
