### ISSUE TITLE
provide min/max with blocks

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/daru#158]
`Daru::Vector#max` doesn't accept a block currently. For example with `Array#max` one can do:

``` ruby
>> dv = Daru::Vector.new ['c', 'bb', 'aaa']
>> dv.max { |i| i.length }
=> "c"     # Wrong because it hasn't been implemented yet
>> ['c', 'bb', 'aaa'].max { |i| i.length }
=> "aaa"

```

**Comment by lokeshh** [comment]
Also I think we should have something like Pandas `argmax()` and `argmin()`, they return the index value at which the value is maximum.

**Comment by v0dro** [comment]
Let's call those methods `index_of_max` and `index_of_min`. And the block is a good idea.

**Comment by athityakumar** [comment]
I believe this issue can be closed now, as it has been taken care of by PR #303 . :smile:
