### ISSUE TITLE
Proposal: Function for filling in missing data

### ISSUE THREAD

**Issue by sunderwood** [SciRuby/daru#198]
I would like to be able to fill or pad the nil values in vectors or data frames. I work primarily with time series data and being able to roll values forward to fill the "missing" spaces is very useful. I have used the python Pandas library before and [Pandas fillna function](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.fillna.html) allows me to fill nil values with a scalar, roll values forward, or roll values backwards.

**Comment by v0dro** [comment]
Yes. That would be useful.

**Comment by rainchen** [comment]
how is this going?
Is there an elegant way of updating missing data like pandas fillna function do?

currently I have to do sth like this:

```
        # fill missing Fare
        df.where(df['Fare'].eq(nil)).each_row_with_index do |row, idx|
          row['Fare'] = 123
          df.set_row_at([idx], row)
        end
```
comparing to `full['Embarked'].fillna('S',inplace=True)`

I'm expecting there is an one-liner solution for daru.

**Comment by v0dro** [comment]
@lokeshh?

**Comment by lokeshh** [comment]
See http://www.rubydoc.info/gems/daru/Daru/DataFrame#replace_values-instance_method

**Comment by v0dro** [comment]
@sunderwood if your issue is resolved can you close this ticket?

**Comment by sunderwood** [comment]
The function that @lokeshh referenced does not fully satisfy my request. I would like to be able to "roll" values forwards or backwards. For example, using the replace_values function example I would expect a `fillna(:forward)` to result in:

```
df = Daru::DataFrame.new({
  a: [1,    2,          3,   nil,        Float::NAN, nil, 1,   7],
  b: [:a,  :b,          nil, Float::NAN, nil,        3,   5,   8],
  c: ['a',  Float::NAN, 3,   4,          3,          5,   nil, 7]
}, index: 11..18)
df.fillna(:forward)
# => #<Daru::DataFrame(8x3)>
#          a   b   c
#   11   1   a   a
#   12   2   b   a
#   13   3   b   3
#   14   3   b   4
#   15   3   b   3
#   16   3   3   5
#   17   1   5   5
#   18   7   8   7
```
and a `fillna(:backward)` to result in: 

```
df = Daru::DataFrame.new({
  a: [1,    2,          3,   nil,        Float::NAN, nil, 1,   7],
  b: [:a,  :b,          nil, Float::NAN, nil,        3,   5,   8],
  c: ['a',  Float::NAN, 3,   4,          3,          5,   nil, 7]
}, index: 11..18)
df.fillna(:backward)
# => #<Daru::DataFrame(8x3)>
#          a   b   c
#   11   1   a   a
#   12   2   b   3
#   13   3   3   3
#   14   1   3   4
#   15   1   3   3
#   16   1   3   5
#   17   1   5   7
#   18   7   8   7
```

**Comment by v0dro** [comment]
Ah. Interesting. Will keep this open.

**Comment by zverok** [comment]
@sunderwood Just curious: what's real-life usage for this "rolling"?..

**Comment by sunderwood** [comment]
One use is financial data. 
A simple example is in order to display a stock's value for every day in a year (including weekends and other non-trading days), existing values would need to roll forward over those dates that don't have data. This accurately represents what the value was on any given date even if the stock wasn't traded.

A more complex example is when running multivariate regressions using stocks and economic data where the reporting dates for all the variables do not line up (economic data is often only reported monthly or quarterly), rolling forward (or backward) the existing data over the "missing" dates is required to include all observed values of the stocks that are traded more frequently.

**Comment by baarkerlounger** [comment]
@sunderwood now that the above PR has been merged can you see if your issue is resolved?
