### ISSUE TITLE
Reset index function

### ISSUE THREAD

**Issue by dansbits** [SciRuby/daru#206]
Is there a function on the data frame similar to the pandas `reset_index` method for adding the values in the index to the dataframe. I often find myself wanting to re-incorporate the index back into my dataframe after using group_by.

I don't see anything and wanted to check before trying to add it.

**Comment by v0dro** [comment]
Should be a good addition. How will the new vector that the index will create be named? Also, the new index that the dataframe will get will be numbered from zero right?
