### ISSUE TITLE
pandas.Index.isin equivalent for daru

### ISSUE THREAD

**Issue by kozo2** [SciRuby/daru#211]
daru can take only an index for `Daru::Index#include?(index)`
On the other hand `pandas.Index.isin` can take a list.

I request the `pandas.Index.isin` equivalent for daru.

**Comment by Shekharrajak** [comment]
```
=> #<Daru::Index(4): {admit, gpa, gre, rank}>
irb(main):018:0> a1 = Daru::Index.new([:admit, :gpa, :gre, :rank])
=> #<Daru::Index(4): {admit, gpa, gre, rank}>
irb(main):019:0> a1.include?('gpa')
=> false
```
Output must be `true`, isn't it ?

**Comment by zverok** [comment]
@kozo2 Sorry for returning to the topic afert a such long time, but can you please explain what is the use case of `pandas.Index.isin`? And am I correct that it returns array _the same size as index_, responding to question "if `i`-th index value included in list provided?" It sounds a bit like "backwards logic" for me.
