### ISSUE TITLE
Better DataFrame summary without reportbuilder

### ISSUE THREAD

**Issue by v0dro** [SciRuby/daru#221]
The `DataFrame#summary` method uses the `reportbuilder` gem for creating a summary of the data. This gem, in addition to being a dependency, was designed keeping `Statsample::Dataset` in mind, which daru moved away from a long time ago.

Thus, a custom implementation for summarizing dataframe contents should be created that does not depend on reportbuilder and shows ample information about the dataframe at a glance.

For reference, here's the output of `#summary` for a data frame:

```
2.2.1 :015 > source_df
 => #<Daru::DataFrame(1x2)>
      col1 col2
    0    1    2 
2.2.1 :016 > puts source_df.summary
= 
  Number of rows: 1
  Element:[col1]
  == col1
    n :1
    n valid:1
  Element:[col2]
  == col2
    n :1
    n valid:1
 => nil 
2.2.1 :017 > 
```

EDIT:
The above example is only a demonstration. The reportbuilder gem is capable of many more things that just the above summary, and before sending a PR for implementing this feature you should go through the documentation of reportbuilder and see what it is capable of and port most (if not all) of those functions to daru w/o introducing new dependencies.

**Comment by krishnak9** [comment]
I am new here. I have a doubt about this "n valid" does that mean the number of column values which are not "nil" or something else.

**Comment by krishnak9** [comment]
I am new here . I have a doubt regarding what `n :1
 n valid:1` signifies here. Does this mean number of rows and number of rows which are not "nil" in a column.

**Comment by v0dro** [comment]
`n valid` is number of elements that are not `nil` or `Float::NAN`. `n` is number of elements.

**Comment by krishnak9** [comment]
Thanks. I want to solve this issue. Will reach out for more help if I got stuck somewhere :smiley:

**Comment by krishnak9** [comment]
In DataFrame the summary is generated by ReportBuilder by using the report_building method of vectors. So we have to remove the ReportBuilder from there too and use a custom method there also. Then we can call that custom method for DataFrame summary too which includes mean,median,mode etc info too about the vectors. Am I missing something here?

**Comment by v0dro** [comment]
Can't really understand what you're trying to say. If you're asking if you'll need to replace report builder in vectors, then yes, you'll have to do that too.

**Comment by ananyo2012** [comment]
Hello I am new here. Can I take a try to solve this issue? I have read the contribution guidelines and did the setup.

**Comment by ananyo2012** [comment]
I made a PR #305 to solve this. Please have a look.
