### ISSUE TITLE
'name' attribute for index

### ISSUE THREAD

**Issue by v0dro** [SciRuby/daru#223]
Addition of an additional 'name' attribute to indexes will simplify their identification and make it easier to know what exactly the index means when printing a data structure.

`MultiIndex` should support having separate names for each level (might be related to https://github.com/v0dro/daru/issues/150).

**Comment by Shekharrajak** [comment]
How to display with Index name in irb : 

right now it is coming like this : 
```
irb(main):005:0> Daru::Index.new [100, 99, 101, 1, 2], name: "index_name"
=> #<Daru::Index(5): {100, 99, 101, 1, 2}>

```

I want this : 

```
irb(main):005:0> Daru::Index.new [100, 99, 101, 1, 2], name: "index_name"
=> #<Daru::Index: index_name(5) {100, 99, 101, 1, 2}>

```
