### ISSUE TITLE
problem with pivot table

### ISSUE THREAD

**Issue by vidok** [SciRuby/daru#24]
Hi, @v0dro 

Thank for your great work!!!  But I have a problem with pivot table

I have next code 

``` ruby
vectors = { visits: [], country:[], city:[], week: [], locale: [], os: [], bounce: [] }
visits.each do |row|
  vectors[:visits].push row.user_count
  vectors[:week].push row.week.to_i
  vectors[:country].push row.country || 'Unknown'
  vectors[:city].push row.city || 'Unknown'
  vectors[:locale].push row.locale || 'Unknown'
  vectors[:os].push row.os || 'Unknown'
  vectors[:bounce].push rand(100)
end
df = Daru::DataFrame.new( vectors )
index = [:week, :country, :os]
table = df.pivot_table(index: index, values: [:visits, :bounce], agg: :sum)
```

result: 
https://gist.github.com/vidok/2845e64b5832746159a8
or write_csv method result https://gist.github.com/vidok/1f61efcb17262bcfbd27

In result log we can see what in some keys is a Daru::Vector rather than numerical values. 
If I change count dimensions from 3 to 2 (eq index = [:week, :country]) than pivot table is valid. 

for which reason this happens?

**Comment by v0dro** [comment]
I think the problem is that the printing of the table is not happening properly. The actual index should be fine.

Could you please verify this by printing the output of `df.index` and `df.vectors`?

Also, you might want to test in the browser based iruby notebook. Printing happens better on the browser than the command line.

**Comment by v0dro** [comment]
Btw how can I reproduce this behavior? Please provide with the data that you are using.

**Comment by vidok** [comment]
Test data https://gist.github.com/vidok/e1c033dddf61972f360b (dumped from real application data)
Test script https://gist.github.com/vidok/6ce3a933ecd0e49872f7 (does the same as in the application)

in my application I use Rails and next code
```ruby
report = Reports::Users.new(@project_id)
table = report.fetch params[:dimensions]
render json: { rows: table.to_a }
```ruby

and when I debug server response in my browser, I see failed structure that I mention above.

**Comment by vidok** [comment]
I have one more error. 
My DataFrame has 1100 rows. When I call pivot_table with 2 index, result is ok. 
Next call pivot_table from DataFrame with 1300 rows, and result is broken. 

http://jsfiddle.net/6ddpdLxw/ ok
http://jsfiddle.net/8h0hqjd1/ broken

I'm not sure that the case in printing output, because I tried many method from Daru::DataFrame and result is identical.

**Comment by zverok** [comment]
Seems to be fixed long time ago!
