### ISSUE TITLE
Suppress warnings if Daru.error_stream is nil

### ISSUE THREAD

**Issue by v0dro** [SciRuby/daru#242]
We should have a module variable called `Daru.error_stream` whose default will be set to `STDERR`, and which can be changed to `nil`. If the user sets it to `nil`, all warnings that are currently printed with `STDERR.puts` should be suppressed.

**Comment by sivagollapalli** [comment]
@v0dro Apart from https://github.com/SciRuby/daru/blob/master/lib/daru.rb#L87 nowhere we are using `STDERR.puts` to print warning messages. I think we can allow an error message if gem didn't installed. Hence I avoided.

**Comment by v0dro** [comment]
@sivagollapalli the reason for this issue is that the errors show up in people's logs every time they require daru in some app. Therefore it makes sense to be able to set a switch.

Setting the switch to `nil` will supress warnings once and for all.

**Comment by baarkerlounger** [comment]
I think this can be closed given the PR merged above?
