### ISSUE TITLE
`Daru::DataFrame.rows` regression: cannot create empty data frames.

### ISSUE THREAD

**Issue by yemartin** [SciRuby/daru#268]
Commit 760fb19 broke creating empty data frames with `Daru::DataFrame#rows`. The following used to work up to commit 2ee4c4c.

Note: this is important because if `source_data` is retrieved dynamically from a database, we have no control when the result may have no rows.

``` ruby
require 'spec_helper.rb'

describe "Daru::DataFrame#rows" do
  it 'can create an empty data frame' do
    source_data = [] # potential result of SomeModel.where(some_condition).pluck(:a, :b, :c)
    expect do
      Daru::DataFrame.rows source_data, order: [:a, :b, :c]
    end.not_to raise_error
  end
end
```

**Comment by zverok** [comment]
I'm on it.
I'm a big fan of breaking things (and probably fix them afterwards)

**Comment by v0dro** [comment]
@zverok any update?

**Comment by zverok** [comment]
Oh damn. I've fixed the issue the next day after it was reported and just forgot to do a PR (some family problems distracted me). Shame on me.
