### ISSUE TITLE
Serious group_by bug

### ISSUE THREAD

**Issue by gnilrets** [SciRuby/daru#281]
Looks like there's a pretty serious bug with group_by when the index isn't a sequential set of integers.

````
wtdf = Daru::DataFrame.new({ g: ['a','a','a'], num: [1,2,3]}, index: [2,12,23])
puts wtdf.sum.inspect
#=> #<Daru::Vector(1)>
#     sum
# num   6

puts wtdf.group_by([:g]).sum.inspect
#=> #<Daru::DataFrame(1x1)>
#     num
#   a   4
````

I think the problem is the way that group_by is making use of indexes:
````
wtdf.group_by([:g])
#=> #<Daru::Core::GroupBy:0x007f9997672950 @groups={["a"]=>[0, 1, 2]}, @non_group_vectors=[:num], @context=#<Daru::DataFrame(3x2)>
#       g num
#   2   a   1
#  12   a   2
#  23   a   3>
````

The groups for the `"a"` category reference indexes `[0, 1, 2]`.  The group_by code is confusing order in the dataframe with the index.  So it first attempts to find index 0, which doesn't exist so it assumes it's the just the first element of the data frame.  Likewise for index 1.  But then it looks for index 2, which does exist, but it's the first record in the dataframe and that's already been counted.

**Comment by v0dro** [comment]
Ok that's bad. Marking as a major bug. @lokeshh @zverok I believe either of you had worked on this? Any leads?

**Comment by zverok** [comment]
Taking a look today.

**Comment by zverok** [comment]
#282 should be the fix.
