### ISSUE TITLE
Rubygems release request

### ISSUE THREAD

**Issue by kozo2** [SciRuby/daru#286]
I confirmed that https://rubygems.org/gems/daru/versions/0.1.4.1 does not fill `Guido` to Lisa's supervisor.
https://gist.github.com/kozo2/5e17baeadf84d71b075bdad215e4bda1/9238fd2ac216c991af5f09eb3c7576b86ffd0a34

While the current master HEAD 70882a9d122f81700e90c4aa2839345207f08d72 works well https://gist.github.com/kozo2/5e17baeadf84d71b075bdad215e4bda1

Could you publish new release to rubygems.org ?

**Comment by v0dro** [comment]
On it.

**Comment by v0dro** [comment]
v0.1.5 has been released.

**Comment by kozo2** [comment]
Thanks
