### ISSUE TITLE
Comparison Operator for Daru::Vector

### ISSUE THREAD

**Issue by genya0407** [SciRuby/daru#287]
`Daru::Vector#>` , which is method alias of `Daru::Vector#gt` , should be much convenient, but it seems that there isn’t such method. Is there any supecial reasons ?
Of course, I think other comparison operators should be also exist.

What I imagine:
```ruby
vector = Daru::Vector.new([1,2,3,4,5])

vector.where((vector > 1) & (vector < 5)) # => Daru::Vector.new([2,3,4])
```

**Comment by v0dro** [comment]
Works. There's no real reason why its not there. I guess I'm lazy.
