### ISSUE TITLE
Kernel dieing for iruby notebook

### ISSUE THREAD

**Issue by ananyo2012** [SciRuby/daru#319]
Whenever I try to start a new instance of iruby notebook inside the daru root directory the kernel dies and restarts and this goes on. I am unable to run any commands in the notebook. Here is the screenshot.
![screenshot from 2017-03-06 04-45-07](https://cloud.githubusercontent.com/assets/10486343/23592505/1fa9f858-0228-11e7-8bc2-76dbbc19c96a.png)
This is similar to this stackoverflow question: http://stackoverflow.com/questions/35999925/kernel-dies-when-creating-iruby-notebook

We should include the `iruby` and `ffi-rzmq` gems as a dependency in the gemspec file.

**Comment by zverok** [comment]
> We should include the iruby and ffi-rzmq gems as a dependency in the gemspec file.

No, we should not (or maybe in a `development` group only). 
It is iruby's problem that it is hard to run system-wide, not daru's. Adding new hard dependency to solve it is not acceptable.

**Comment by db579** [comment]
This could probably be solved with more thorough guides to installing dependencies and getting them working on various systems in a readme or common issues wiki type thing?

**Comment by ananyo2012** [comment]
@zverok We can add this as an development dependency. Thoughts on this ?

**Comment by v0dro** [comment]
No. This is purely an iruby issue and should be dealt with in the iruby issue tracker. The Kernel will die before daru can even be required. What's the use of introducing a development dependency in daru?

Check out the iruby issue tracker, many people have posted this problem and offered solutions.
