### ISSUE TITLE
Loading a headers only csv should create empty DataFrame with headers

### ISSUE THREAD

**Issue by parthm** [SciRuby/daru#349]
Trying to load a CSV with only headers errors out right now. It would be better it an empty DataFrame is created with the headers.
Daru: 0.1.5
Ruby: 2.3.3
File attached as zip as CSV attachments are not supported.
[column_headers_only.zip](https://github.com/SciRuby/daru/files/1040675/column_headers_only.zip)

As it stands now a the CSV file needs to be loaded and checked if empty before we can load it.

```
user@vbox:~/tmp$ cat column_headers_only.csv 
col0,col1,col2
user@vbox:~/tmp$ pry
[1] pry(main)> require 'daru'
=> true
[2] pry(main)> df = Daru::DataFrame.from_csv('column_headers_only.csv')
NoMethodError: undefined method `size' for nil:NilClass
from /home/user/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/daru-0.1.5/lib/daru/dataframe.rb:2383:in `initialize_from_hash_with_arrays'
[3] pry(main)> 
```

**Comment by zverok** [comment]
Accepted.

**Comment by info-rchitect** [comment]
As a temporary workaround I did this:

~~~ruby
headers = CSV.open(mycsv, &:readline)
daru_hash = {}.tap do |daru|
  headers.each {|h| daru[h] = []}
end
my_dataframe = Daru::Dataframe.new(daru_hash, order: headers)
~~~

**Comment by athityakumar** [comment]
This has been fixed in daru-io with https://github.com/athityakumar/daru-io/pull/33
