### ISSUE TITLE
symbols as column headers via symbol_headers=true|false option to from_csv

### ISSUE THREAD

**Issue by parthm** [SciRuby/daru#362]
While reading a CSV, it might be convenient to optionally have headers be symbols instead of strings. As of now I just read the CSV and convert the convert the headers using the code below.
```ruby
  df.vectors = Daru::Index.new(df.vectors.to_a.map(&:downcase).map(&:to_sym))
```
This allows us to conveniently access vector content `v[:foo]` and dataframe vectors `df[:bar]` which arguably is a more ruby like way to access values. This is intuitive as symbols are frequently used as keys for ruby data structures. Perhaps a flag like `symbol_headers=true|false` can be supported in the `from_csv` method. While writing, they symbols are obviously stored as strings and nothing changes at that front.

**Comment by gnilrets** [comment]
You can use whatever header converters you want by options to the standard Ruby CSV parser (http://ruby-doc.org/stdlib-2.0.0/libdoc/csv/rdoc/CSV.html#method-i-header_converters).  Here's one way to get what you want:

```
df = Daru::DataFrame.from_csv myfile, { headers: true, header_converters: CSV::HeaderConverters[:symbol] }
```

**Comment by parthm** [comment]
Ah. Perfect. Thanks for pointing it out @gnilrets . I was not aware of that.

**Comment by v0dro** [comment]
I think problem is solved. Closing.
