### ISSUE TITLE
Remove post-install message

### ISSUE THREAD

**Issue by zverok** [SciRuby/daru#406]
Post-install messages are bad taste, and should be used ONLY for notifying about breaking changes (like "You are installing Daru 2.0, for porting from Daru 1.0 look at instructions [here]"

**Comment by v0dro** [comment]
Ok. I kinda like the beer mug though :P

**Comment by athityakumar** [comment]
@v0dro - Me too. It was one of the "crazy inspirations" that made me interested in daru even without looking at the codebase. An impressive first impression, if you will. I was about to add it to daru-io too, but with a straw in the beer mug symbolizing the Import / Export of Daru. 😄 

> Art requires sacrifices!

Sad reacts only. 😢

**Comment by v0dro** [comment]
@zverok alright.

**Comment by zverok** [comment]
Done in `master`.
