### ISSUE TITLE
Request for discussion: Index unicality

### ISSUE THREAD

**Issue by zverok** [SciRuby/daru#432]
cc @v0dro @lokeshh (and everyone who is interested in Daru future are welcome! especially guys who use Daru in complicated production tasks, @info-rchitect? @genya0407?)

What we have now:
* `Index` may have only unique values;
* `CategoricalIndex` may have non-unique values.

Now:
* "Intuitively", Index (which is "labels" or "axis" for our data) should _always_ be unique, any other behavior doesn't make any sense: Index is what allows you, well, _index_ your data, and unambiguous correspondence from label to row is important.
* On the other hand, pandas' indexes are non-unique, and not as a design error, but as a special _feature_ in [ver. 0.8.0](https://pandas.pydata.org/pandas-docs/stable/whatsnew.html#support-for-non-unique-indexes), so, there should be some use cases that require this feature?..

The only thing that comes to mind is supporting "dirty" data (e.g. I am loading data from some `.csv`, saying that first column should be index, and it turns out that it has duplicate values, and instead of "Error: Can't load non-unique data" I obtain valid DataFrame, which can be examined and cleaned up). Is there any other reasonable use cases?

This way or that, I believe that all indexes should be consistent: either allow duplicate values, or forbid them. 

I'd like to understand clearly what is the most reasonable solution.

**Comment by info-rchitect** [comment]
@zverok I agree with your statement on index uniqueness, intuitively they should always be unique.  It would be helpful to see the pandas spec tests for such a non-unique index.  it would seem to be a drastic and huge leap to change to non-unique indices.

**Comment by baarkerlounger** [comment]
I also think indexes should be unique and it seems weird Pandas allows that. To me that's what categorical indexes are for. For the use case of importing dirty data from csv we now have the `.uniq` method on dataframe for cleaning duplicate values.

**Comment by lokeshh** [comment]
Use cases for categorical index:

1. When you want constant time lookup with a column that's non unique

2. Since we have daru-io integrating web databases with data frames, index
uniqueness is not a restriction on databases. Imposing it on data frames
would be a problem.

**Comment by zverok** [comment]
@lokeshh 

> 1. When you want constant time lookup with a column that's non unique

But what is _logical_ use case here? I don't believe "design, driven by optimization" is really a good thing.

> 2. Since we have daru-io integrating web databases with data frames, index
uniqueness is not a restriction on databases. Imposing it on data frames
would be a problem.

Our index is "axis labels", nothing in common with DB index (which is access optimizer), and we don't import indexes from DB.

**Comment by lokeshh** [comment]
How about a vector where data value is country name and index is the
continent these countries belong to? If we restrict index to be unique, we
won't be able express this vector.

**Comment by zverok** [comment]
@lokeshh but what would be physical meaning of this vector?
By definition, a vector is an ordered list of values; and the index is an _axis labels_ for this values. Each label corresponds to exactly one value (or exactly one row in dataframe case). `MultiIndex` adds label clustering, `DateTimeIndex` adds slicing by time periods, but both preserve the invariant of "each value has its own label".

What kind of axis it is, which has same labels for different positions on axis? How can it be used in practice?

**Comment by gnilrets** [comment]
Why wouldn't you just use a two-vector dataframe to represent the continent-country situation?

**Comment by lokeshh** [comment]
Do you agree that index is a way to label data? If so then this vector can
be thought of as a set of countries labeled by continents. Now why should
we restrict labeling to be unique?

**Comment by zverok** [comment]
> Do you agree that index is a way to label data?

To **provide axis labels**, not to label any data with anything. 
Unless you'll show some real use case (with code, preferably), not theoretical one "we can say that apples are labels for oranges, how Vector handles this?"

**Comment by baarkerlounger** [comment]
Shouldn't the country/continent case be a categorical index? The continent is a category that can have multiple values...

**Comment by gnilrets** [comment]
I still don't understand why we need the index to represent anything.  It really seems to me that an integer index would work and be far simpler to implement.

What can you accomplish with an index that represents meaningful data (like continent) that you can't accomplish with a 2-vector dataframe?

Certainly there will be some syntax differences: e.g., `myvec['europe']` vs `mydf.where[mydf['country'].eq('europe')`.  But really, I don't get why indexes have to contain data.

**Comment by lokeshh** [comment]
Hands down. Let's go for index uniqueness. It doesn't restrict any use case
functionally but just a theoretical restriction for me which isn't such a
big deal I guess.

**Comment by zverok** [comment]
Thanks everybody! Let it be so.
