### ISSUE TITLE
Inconsistency of parentheses in method parameters

### ISSUE THREAD

**Issue by Kamalpaneru** [SciRuby/daru#437]
I was just looking at some parts of the code and found inconsistency. Is this intentional?? <br>
 lib/daru/vector.rb

![each_index](https://user-images.githubusercontent.com/13826932/32051828-e1a264c6-ba75-11e7-8a78-8558fe468fdf.jpg)
![each_with_index](https://user-images.githubusercontent.com/13826932/32051838-eb1b7aa6-ba75-11e7-957f-dd6b872a1a83.jpg)

**Comment by zverok** [comment]
@Kamalpaneru that's how it is historically.
Is about to be fixed on the road to 1.0 (see v-1-pre branch).

**Comment by Kamalpaneru** [comment]
Great!! You guys are doing some awesome work... Keep up the great work :+1:
