### ISSUE TITLE
V0.2.0 release changelog

### ISSUE THREAD

**Issue by baarkerlounger** [SciRuby/daru#439]
https://github.com/SciRuby/daru/releases has no changelog for V0.2.0

**Comment by zverok** [comment]
Hm. Indeed. Dumb question: how is that filled? Never used this GitHub feature. @v0dro? Should've I write that before the release or what?

**Comment by athityakumar** [comment]
@zverok - It's supposed to be written after the release. You must be seeing a "Edit release" button on the releases page - you've to copy-paste the changelog part for v0.2.0 there.

**Comment by zverok** [comment]
https://github.com/SciRuby/daru/releases/tag/v0.2.0 Here we go. Thanks for reminder!
