### ISSUE TITLE
Alternate method for `access_row_tuples_by_indexs`

### ISSUE THREAD

**Issue by Prakriti-nith** [SciRuby/daru#462]
Recently, `access_row_tuples_by_indexs` method has been removed from daru. Please let us know the alternative.
Refer: [#454](https://github.com/SciRuby/daru/pull/454#pullrequestreview-133706760), [Sciruby/daru-view#103 (issue)](https://github.com/SciRuby/daru-view/issues/103)

**Comment by Shekharrajak** [comment]
@Prakriti-nith , please create a PR in daru repo and putting the same method in same place (revert the changes for this method) with testcases. 

Thanks!
