### ISSUE TITLE
Ideas For Improving Daru & Making It More User-Friend

### ISSUE THREAD

**Issue by matugm** [SciRuby/daru#478]
Hi,
I really like Daru & I would like it to be more popular so I have a few suggestions that I believe will help increase adoption.

1. **Improve documentation**. I think the notebooks are great, but I can't find all the options available for creating a plot.

For example, if I want to give a title to my plot, the logical way I think would be `plot.title`, but it doesn't work (Nyaplot NoMethodError).

2. **Improve error messages & error handling**. If I create a `bar` plot missing an `y` value I get a very confusing error (as a Daru user):

> NoMethodError (undefined method `to_sym' for nil:NilClass)

Wouldn't it be more user-friendly if it said "please provide a valid x value"?

3. **When exporting a plot to HTML**, I get what looks like some random number (`22452`), as a Daru user that doesn't explain to me what just happened.

How about printing the full path of the file that was created? Wouldn't that be more helpful?

Thank you!

**Comment by Shekharrajak** [comment]
Hi @matugm ,

Thanks for sharing this. Yes, you can open separate issues for class method documentations, unwanted errors; stating the improvement (and someone will surely look into it). Related to plotting a graph, feel free to open issue in daru-view repo.

**Comment by v0dro** [comment]
@matugm I like your suggestions. Can you open them in separate issues so that we can triage and tackle each of them independently?
