### ISSUE TITLE
release 0.2.2, or at least as pre?

### ISSUE THREAD

**Issue by Yuki-Inoue** [SciRuby/daru#498]
Since 0.2.1, several improvements are merged into master.  Is it possible to release them as `0.2.2`?  Or, at least as `0.2.2.pre` ?

**Comment by Shekharrajak** [comment]
Ping @v0dro

**Comment by kojix2** [comment]
Daru::View require the latest Daru. I hope Daru::View work with RubyData’s Docker image.
https://github.com/RubyData/docker-stacks

This image will be added to try Jupyter page. 
https://jupyter.org/try

**Comment by kojix2** [comment]
http://bestgems.org/gems/daru

It's good time to release a new version. 
![image](https://user-images.githubusercontent.com/5798442/56879833-65142080-6a95-11e9-9c36-69672e3028c0.png)

50-250 downloads / day
![image](https://user-images.githubusercontent.com/5798442/56879926-c0461300-6a95-11e9-9d22-090ad4578432.png)

**Comment by Shekharrajak** [comment]
Thanks @kojix2 for information. I will work on it by this weekend.

**Comment by kojix2** [comment]
I am waiting for a new version.
Where is the obstacle to the release of a new version now?

**Comment by Shekharrajak** [comment]
Actually, I am bit busy and we need to write Enhancements/Fixes/New feature PRs in https://github.com/SciRuby/daru/blob/master/History.md and https://github.com/SciRuby/daru/releases, which is time taking.

**Comment by kojix2** [comment]
Ok. So we need to summarize the commit log.
https://github.com/SciRuby/daru/compare/v0.2.1...master

**Comment by Shekharrajak** [comment]
Yes! May be in future we can have a bot that handles release note automatically whenever new commits are merged.

Also, we need to change the version here : https://github.com/SciRuby/daru/blob/master/lib/daru/version.rb according to the changes and feature added.

**Comment by kojix2** [comment]
@v0dro Could you please add @shahsaurabh0605 to owner of daru.gem on rubygems.org?
https://rubygems.org/gems/daru

https://github.com/SciRuby/iruby/issues/211

**Comment by kojix2** [comment]
You can upgrade it twice.

Most of the changes in the first half of https://github.com/SciRuby/daru/compare/v0.2.1...master were made by Yuki Inoue, so he writes a release note.
Then @Shekharrajak  release it once.

The second half is mostly from Shekharrajak, so it's not hard to write release notes.
Then there's the second release.

**Comment by Shekharrajak** [comment]
Okay, I will do it as soon as possible. I think in near future we can have a bot who writes the release note (may be in wiki page) after merging any PR.

**Comment by Shekharrajak** [comment]
Checkout the new version 0.2.2 at https://rubygems.org/gems/daru and changelog : https://github.com/SciRuby/daru/blob/master/History.md#022-8-august-2019

**Comment by kojix2** [comment]
Great!
