### ISSUE TITLE
Make daru compatible with Ruby >= 2.5

### ISSUE THREAD

**Issue by Shekharrajak** [SciRuby/daru#505]
Related discussion:   #500,  #503

**Comment by kojix2** [comment]
https://github.com/SciRuby/packable/issues/4#issuecomment-481443915

**Comment by kojix2** [comment]
https://github.com/SciRuby/packable/commit/4ee8456a5f322992bf32de3a760f2ae482410711
@marcandre take back maintenance!!! 🎉 🎉 🎉

**Comment by Nakilon** [comment]
The above links are 404 now.
