### ISSUE TITLE
Suggestion: DataFrame to two-dimensional array 

### ISSUE THREAD

**Issue by janmpeterka** [SciRuby/daru#524]
I need two-dimensional array as training data in linear regression.
So, I would like to add following method (maybe with some better name) to `Daru::DataFrame`

```ruby
#dataframe.rb

def to_multi_a
    each_row.map(&:to_a)
end
``` 
used like this

```ruby
multi_array = data_frame.to_multi_a
```

Thoughs?
Better ways to do this?

Thanks for reactions :)

**Comment by kojix2** [comment]
Hello. Daru is not so active these days... 
But I use the following idiom to get 2d array. 
```
df.to_matrix.to_a
```

**Comment by janmpeterka** [comment]
Thanks @kojix2, closing this issue

**Comment by javadba** [comment]
> Hello. Daru is not so active these days...
Really? I do see recent activity.  I am looking for the ruby equivalent of R's data.table . Is this the most active repo for it?

**Comment by kojix2** [comment]
I think Daru is the best datatable in Ruby and there is no alternative project. 

The local ruby community in Japan is interested in [Apache Arrow](https://arrow.apache.org/). But it's not a global trend right now. ApacheArrow is the project of Wes McKinney, the original creator of [pandas](https://github.com/pandas-dev/pandas), and is expected to be the backend for pandas in the future. 

Sure, Apache Arrow will improve performance. But it doesn't answer the question of what Ruby data tables should be like? 

I think Daru is an elegant answer to that question. But It's not perfect. It's a developing one...
